name: Run API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Added step to set up test coverage
      - name: Create test results directory
        run: mkdir -p test-results

      - name: Run tests
        run: npm test -- --coverage --testResultsProcessor="jest-junit"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL || 'postgresql://test:test@localhost:5432/test-db' }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'test-secret' }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL || 'http://localhost:3000' }}
          JEST_JUNIT_OUTPUT_DIR: "test-results"

      # Added step to save test results and coverage reports
      - name: Upload test results
        if: always() # Run even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test-results
            coverage